//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALCompact
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeetingsLocalEntities : DbContext
    {
        public MeetingsLocalEntities()
            : base("name=MeetingsLocalEntities")
        {
        }

        public MeetingsLocalEntities(string connectionString) : base(connectionString) { }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Meeting> Meeting { get; set; }
    }
}
